---
- name: "Compactor: Install thanos compact systemd file"
  template:
    src: thanos-compactor.j2
    dest: /etc/systemd/system/thanos-compactor.service
  register: compact_systemd
  notify: restart thanos-compactor

- name: "Compactor: Reload systemd if thanos compact changed"
  systemd:
    daemon_reload: true

- name: "Compactor: Add defaults file"
  template:
    src: thanos-compactor-defaults.j2
    dest: /etc/default/thanos-compactor
  notify: restart thanos-compactor

- name: "Compactor: generate configuration file"
  template:
    group: prometheus
    src: thanos-s3-config.j2
    dest: "{{ thanos_compactor_config_file }}"
  notify: restart thanos-compactor

- name: "Compactor: Ensure thanos-compactor is started"
  service:
    name: thanos-compactor
    enabled: true
    state: started

- name: "Check if node exporter directory exists"
  stat:
    path: /etc/prometheus-node-exporter
  register: node_exporter

- name: "Add node exporter files"
  when: node_exporter.stat.exists is defined and node_exporter.stat.exists
  block:
    - set_fact: service_name="thanos-compactor"

    - name: "Add the node exporter file to path"
      template:
        src: node-exporter.sh.j2
        dest: /usr/local/bin/prometheus-service-restart.sh
        owner: root
        group: root
        mode: 0775

    - name: "Set up cronjob for node exporter"
      cron:
        name: "Run systemd restart count"
        minute: "*/1"
        job: "/usr/local/bin/prometheus-service-restart.sh"
